// apps/web-react/src/app/app.tsx

import { useEffect, useState } from 'react';
import type { Project } from '@fullstack-nx18-workspace/domain-model';
import { fetchProjects } from '@fullstack-nx18-workspace/api-client';

export function App() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      try {
        setLoading(true);
        setError(null);

        const data = await fetchProjects();
        if (!cancelled) {
          setProjects(data);
        }
      } catch (err) {
        console.error('Failed to load projects:', err);
        if (!cancelled) {
          setError('Could not load projects. Please try again.');
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    load();

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <main style={{ padding: '1.5rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1>Fullstack Nx18 Workspace – Projects</h1>

      {loading && <p>Loading projects...</p>}

      {error && (
        <p style={{ color: 'red' }}>
          {error}
        </p>
      )}

      {!loading && !error && projects.length === 0 && (
        <p>No projects found. Try running <code>npm run db:seed</code>.</p>
      )}

      {!loading && !error && projects.length > 0 && (
        <ul style={{ marginTop: '1rem', listStyle: 'none', padding: 0 }}>
          {projects.map((project) => (
            <li
              key={project.id}
              style={{
                padding: '0.75rem 1rem',
                marginBottom: '0.5rem',
                borderRadius: '0.5rem',
                border: '1px solid #e5e7eb',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
              }}
            >
              <div>
                <strong>{project.name}</strong>
                <div style={{ fontSize: '0.85rem', color: '#6b7280' }}>
                  Created: {new Date(project.createdAt).toLocaleString()}
                </div>
              </div>
              <span
                style={{
                  padding: '0.25rem 0.5rem',
                  borderRadius: '999px',
                  fontSize: '0.75rem',
                  border: '1px solid #d1d5db',
                  background:
                    project.status === 'ACTIVE' ? '#dcfce7' : '#e5e7eb',
                }}
              >
                {project.status}
              </span>
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}

export default App;

// apps/web-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ProjectsService } from './projects.service';
import { Project } from '@fullstack-nx18-workspace/domain-model';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  title = 'Fullstack Nx18 Angular – Projects';
  loading = true;
  error: string | null = null;
  projects: Project[] = [];

  constructor(private projectsService: ProjectsService) {}

  ngOnInit(): void {
    this.projectsService.getProjects().subscribe({
      next: (projects) => {
        this.projects = projects;
        this.loading = false;
      },
      error: (err) => {
        console.error('Failed to load projects (Angular):', err);
        this.error = 'Could not load projects. Please try again.';
        this.loading = false;
      },
    });
  }
}

<main style="padding: 1.5rem; font-family: system-ui, sans-serif">
  <h1>{{ title }}</h1>
  <p>This is the Angular client using the same API and domain model.</p>

  <section *ngIf="loading">
    <p>Loading projects...</p>
  </section>

  <section *ngIf="error">
    <p style="color: darkred">{{ error }}</p>
  </section>

  <section *ngIf="!loading && !error">
    <ul *ngIf="projects.length > 0; else noProjects">
      <li *ngFor="let project of projects">
        <strong>{{ project.name }}</strong>
        <span> — {{ project.status }}</span>
        <div style="font-size: 0.85rem; color: #555">
          {{ project.description }}
        </div>
        <div style="font-size: 0.8rem; color: #777">
          Created: {{ project.createdAt | date: 'medium' }}
        </div>
      </li>
    </ul>

    <ng-template #noProjects>
      <p>No projects yet. Try seeding or creating some.</p>
    </ng-template>
  </section>
</main>
