// apps/mobile-expo/src/app/App.tsx
import React, { useEffect, useState } from 'react';
import { SafeAreaView, View, Text, FlatList, ActivityIndicator, StyleSheet } from 'react-native';
import type { Project } from '@fullstack-nx18-workspace/domain-model';
import { fetchProjects } from '@fullstack-nx18-workspace/api-client';

export default function App() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let mounted = true;

    async function load() {
      try {
        const data = await fetchProjects();
        if (mounted) {
          setProjects(data);
          setError(null);
        }
      } catch (err) {
        console.error('Failed to load projects (mobile):', err);
        if (mounted) {
          setError('Could not load projects. Please try again.');
        }
      } finally {
        if (mounted) {
          setLoading(false);
        }
      }
    }

    load();

    return () => {
      mounted = false;
    };
  }, []);

  return (
    <SafeAreaView style={styles.container}>
      <Text style={styles.title}>Fullstack Nx18 Workspace – Mobile Projects</Text>

      {loading && <ActivityIndicator size="large" />}

      {error && !loading && (
        <Text style={styles.error}>{error}</Text>
      )}

      {!loading && !error && (
        <FlatList
          data={projects}
          keyExtractor={(item) => item.id}
          contentContainerStyle={styles.list}
          renderItem={({ item }) => (
            <View style={styles.card}>
              <Text style={styles.name}>{item.name}</Text>
              {/* description may be optional; guard it */}
              {item.description && (
                <Text style={styles.description}>{item.description}</Text>
              )}
              <Text style={styles.meta}>
                Status: {item.status} • Created: {new Date(item.createdAt).toLocaleString()}
              </Text>
            </View>
          )}
        />
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    paddingTop: 32,
    backgroundColor: '#020617',
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    color: '#e5e7eb',
    marginBottom: 16,
  },
  error: {
    color: '#f97316',
    marginTop: 8,
  },
  list: {
    paddingBottom: 24,
  },
  card: {
    backgroundColor: '#0f172a',
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  name: {
    fontSize: 16,
    fontWeight: '600',
    color: '#f9fafb',
    marginBottom: 4,
  },
  description: {
    fontSize: 14,
    color: '#cbd5f5',
    marginBottom: 4,
  },
  meta: {
    fontSize: 12,
    color: '#9ca3af',
  },
});

// apps/web-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ProjectsService } from './projects.service';
import { Project } from '@fullstack-nx18-workspace/domain-model';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  title = 'Fullstack Nx18 Angular – Projects';
  loading = true;
  error: string | null = null;
  projects: Project[] = [];

  constructor(private projectsService: ProjectsService) {}

  ngOnInit(): void {
    this.projectsService.getProjects().subscribe({
      next: (projects) => {
        this.projects = projects;
        this.loading = false;
      },
      error: (err) => {
        console.error('Failed to load projects (Angular):', err);
        this.error = 'Could not load projects. Please try again.';
        this.loading = false;
      },
    });
  }
}

<main style="padding: 1.5rem; font-family: system-ui, sans-serif">
  <h1>{{ title }}</h1>
  <p>This is the Angular client using the same API and domain model.</p>

  <section *ngIf="loading">
    <p>Loading projects...</p>
  </section>

  <section *ngIf="error">
    <p style="color: darkred">{{ error }}</p>
  </section>

  <section *ngIf="!loading && !error">
    <ul *ngIf="projects.length > 0; else noProjects">
      <li *ngFor="let project of projects">
        <strong>{{ project.name }}</strong>
        <span> — {{ project.status }}</span>
        <div style="font-size: 0.85rem; color: #555">
          {{ project.description }}
        </div>
        <div style="font-size: 0.8rem; color: #777">
          Created: {{ project.createdAt | date: 'medium' }}
        </div>
      </li>
    </ul>

    <ng-template #noProjects>
      <p>No projects yet. Try seeding or creating some.</p>
    </ng-template>
  </section>
</main>
